stubs: fix default CPU clock definition
zephyrproject-rtos/hal_espressif pull request #166
Opened 2022-12-21 12:23 UTC by sylvioalves

Retrieve CPU clock from DTS instead of custom CONFIG value. For ESP32 and ESP32-S2 where the CPU clock is linked to CCOUNT, it works as is. For ESP32-C3 where systimer is used, it does not work.

Signed-off-by: Sylvio Alves <sylvio.alves@espressif.com>

2022-12-22 12:49 UTC, marekmatej requested changes
Better to replace `ESP_SOC_DEFAULT_CPU_FREQ_MHZ` by `CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC`

2022-12-23 12:19 UTC, sylvioalves commented
> CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC

I think it won't work. `CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC` is not always `cpu_clock` provided in device tree. In case o ESP32 and ESP32-S2, it is. For ESP32-C3, it is not. `CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC` in ESP32-C3 is the 16MHz timer clock reference. So better to keep this change.

2022-12-26 01:19 UTC, sylvioalves commented
@marekmatej @LucasTambor Any feedbacks?

2022-12-26 12:13 UTC, LucasTambor approved these changes

2022-12-28 11:42 UTC, marekmatej approved these changes
LGTM

2022-12-28 13:35 UTC, merged