wifi: move wifi porting to hal
zephyrproject-rtos/hal_espressif pull request #9
Opened 2021-02-03 16:47 UTC by sylvioalves

all porting related sources moved to hal repository

Signed-off-by: Sylvio Alves <sylvio.alves@espressif.com>

2021-02-04 06:47 UTC, mahavirj requested changes

2021-02-04 06:47 UTC, mahavirj commented on zephyr/adapter/include/wifi/esp_wifi_system.h
> +
Missing header file guards here (`#pragma once`)

2021-02-04 06:47 UTC, mahavirj commented on zephyr/adapter/src/wifi/esp_event.c
> +	event_msgq_buffer = k_malloc(sizeof(system_event_t) * 10);
Can you please checking coding style here once?

2021-02-04 06:47 UTC, mahavirj commented on zephyr/adapter/src/wifi/esp_system_api.c
> +	ESP_LOGE(TAG, "mac address param is NULL");
Please check coding style once for this file

2021-02-04 06:47 UTC, mahavirj commented on zephyr/adapter/include/wifi/esp_networking_priv.h
> +#ifndef ESP_NETWORKING_PRIV_H
Should we change this to `#pragma once` for consistency?

2021-02-04 09:36 UTC, sylvioalves commented
@mahavir, I have pushed the wrong files. That's the reason for all the missing code style.

2021-02-05 04:21 UTC, mahavirj approved these changes

2021-02-05 12:30 UTC, merged